[package]
name = "rusty-loader"
version = "0.2.6"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>", "Colin Finck <colin.finck@rwth-aachen.de>"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"

[features]
aarch64-qemu-stdout = []    # Output to special qemu address 0x3F20_1000 instead of trying to use uart

[dependencies]
bitflags = "1.3"
goblin = { version = "0.4.1", default-features = false, features = ["elf64", "elf32", "endian_fd"] }

[target.'cfg(target_arch = "x86_64")'.dependencies]
multiboot = "0.7"
x86 = { version = "0.41", default-features = false }

[build-dependencies]
target_build_utils = "0.3"

# The release profile, used for `cargo build --release`.
[profile.dev]
opt-level = 1      # controls the `--opt-level` the compiler builds with
debug = true       # controls whether the compiler passes `-C debuginfo`
                   # a value of `true` is equivalent to `2`
rpath = false      # controls whether the compiler passes `-C rpath`
lto = false         # controls `-C lto` for binaries and staticlibs
debug-assertions = true # controls whether debug assertions are enabled

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
