[package]
name = "rusty-loader"
version = "0.2.6"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>", "Colin Finck <colin.finck@rwth-aachen.de>"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2021"

[dependencies]
bitflags = "1.3"
goblin = { version = "0.4", default-features = false, features = ["elf64", "elf32", "endian_fd"] }
static-alloc = "0.2"

[target.'cfg(target_arch = "x86_64")'.dependencies]
multiboot = "0.8"
x86 = { version = "0.45", default-features = false }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64 = "0.0.7"

[profile.dev]
opt-level = 1  # `opt-level = 0` makes bootloader to large for bootstrapping

[profile.release]
strip = "debuginfo"
lto = true
codegen-units = 1
