[package]
name = "rusty-loader"
version = "0.2.6"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>", "Colin Finck <colin.finck@rwth-aachen.de>"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2021"

[dependencies]
goblin = { version = "0.5", default-features = false, features = ["elf64"] }
plain = "0.2"
static-alloc = "0.2"

[target.'cfg(target_arch = "x86_64")'.dependencies]
bitflags = "1.3"
multiboot = "0.8"
x86 = { version = "0.48", default-features = false }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64 = "0.0.7"
align-data = "0.1"

[build-dependencies]
cc = "1.0"
nasm-rs = "0.2"

[profile.release]
strip = "debuginfo"
lto = true
codegen-units = 1

[workspace]
members = [
	"xtask",
]
