[package]
name = "rusty-loader"
version = "0.4.0"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>", "Colin Finck <colin.finck@rwth-aachen.de>"]
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2021"

[dependencies]
hermit-entry = { version = "0.9", features = ["loader"] }
log = "0.4"

[target.'cfg(all(target_os = "none", target_arch = "x86_64"))'.dependencies]
multiboot = "0.8"

[target.'cfg(target_arch = "x86_64")'.dependencies]
bitflags = "1.3"
uart_16550 = "0.2"
x86_64 = { version = "0.14", default-features = false }

[target.'cfg(target_arch = "aarch64")'.dependencies]
aarch64 = "0.0.7"
align-data = "0.1"

[target.'cfg(target_os = "uefi")'.dependencies]
uefi = { version = "0.18", features = ["exts"] }
uefi-services = "0.13"

[build-dependencies]
cc = "1.0"
nasm-rs = "0.2"

[profile.release]
strip = "debuginfo"
lto = true
codegen-units = 1

[workspace]
members = [
	"xtask",
]
